### ISSUE TITLE
Compare images

### ISSUE THREAD

**Issue by Gulivertx** [Gulivertx/synology-photos-auto-sort#3]
Try to implement base64 images compare to avoid copy all images with a same name in error folder, but if the image is not the same copy in target folder with a new name.

https://softwarerecs.stackexchange.com/questions/9774/command-line-tool-to-check-whether-two-images-are-exactly-the-same-graphically

**Comment by kalnak** [comment]
Hi, I'm sort of limited in trying to do it myself. Why I asked if it was possible was becuase your script actually helped my alot. Had over 100k pictures that got sorted but 15k of those went to error folder even thoght they werent copies. The pictures taken is from several devices so somehow the script thought they were copies/clones.

Would have been nice if it was possible to "upgrade" the script to skip the error part and let it rename the pictures with_001 or something.

But this command that compares pictures would actually be better if possible to add.

**Comment by Gulivertx** [comment]
Ok sounds like for your case there is a need, I'm gonna implement a new script argument to always copy duplicate files in same time of the base64 compare.

**Comment by Vedeneb** [comment]
I just stumpled upon that script and it works almost perfect for my scenario, however I would also like to have the files beeing renamed if a file with the same name exists instead of moving it to the error folder. It happens that I take more than one image per second, which would cause this script to move these images to the error folder.

Thanks :)

**Comment by Gulivertx** [comment]
Now available with the last version of the script commit right now ! 
https://github.com/Gulivertx/synology-photos-auto-sort/commit/9748bae9ba7bc98f18f60c570bc35cb7bc011e5f

**Comment by Gulivertx** [comment]
PLease could you tell me if this new feature is enough by testing it before I implement a force rename option
