### ISSUE TITLE
Get file name - failes with dropbox files

### ISSUE THREAD

**Issue by Merwenus** [Gulivertx/synology-photos-auto-sort#5]
Dropbox downloads pictures to my synology server and I want to move them to specific folder, but it seems this script does not get the original file name properly so it fails to rename and move.

https://logout.hu/dl/upc/2020-10/122010_6656.png

Original file name: `2020-09-27 12.07.37.jpg`
After getfilename: `Error: File not found - 12.07.37.jpg`

**Comment by Gulivertx** [comment]
please verify what exiftool give has information with the command exiftool ${FILE} | grep -a -i "create date" | head -1 | xargs.

EDIT : I think it's related to this issue [escape](https://github.com/Gulivertx/synology-photos-auto-sort/issues/6)
