### ISSUE TITLE
File not found error caused by spaces in the file names

### ISSUE THREAD

**Issue by cristianbaciu** [Gulivertx/synology-photos-auto-sort#6]
The script will fail to move the files if there are spaces in the file paths or in the file names of the pictures.

You will get an error like "Error: File not found - 2908.JPG". 

The fix is to escape the spaces for all variables.

**Comment by Gulivertx** [comment]
thank's for report, ok I will mention that in the readme, currently I do not plane any change for that, but if you want I will appreciate PR :)
