### ISSUE TITLE
grep misinterpreting the input as binary

### ISSUE THREAD

**Issue by kaili82** [Gulivertx/synology-photos-auto-sort#7]
executing
DATETIME=$(exiftool ${FILE} | grep -i "create date" | head -1 | xargs)
returns DATETIME = "Binary file (standard input) matches".
Therefore, the script doesn't work on my synology.

Solution:
add the option -a to make grep treat the input as text.
Therefore, please replace the line with 
DATETIME=$(exiftool ${FILE} | grep -a -i "create date" | head -1 | xargs)

**Comment by Gulivertx** [comment]
Thanks, now fixed with new option -a
